// <auto-generated />
namespace ALCT.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addContato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addContato));
        
        string IMigrationMetadata.Id
        {
            get { return "201311071259279_addContato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
